AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation template for RDS Aurora

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: Identifier for the RDS instance
    Default: MyDBInstance
  DBMasterUsername:
    Type: String
    Description: Master username for the RDS instance
    Default: admin
  DBMasterPassword:
    Type: String
    Description: Master password for the RDS instance
    Default: MySecretPassword

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      AvailabilityZones:
        - us-east-1a
      Engine: aurora
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      DatabaseName: MyDatabase
      BackupRetentionPeriod: 7

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: db.t2.micro
      Engine: aurora
      DBClusterIdentifier: !Ref DBCluster
      AutoMinorVersionUpgrade: true

Outputs:
  DBClusterEndpoint:
    Description: Endpoint of the Aurora DB Cluster
    Value: !GetAtt DBCluster.Endpoint.Address
  DBInstanceEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt DBInstance.Endpoint.Address
