AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal IAM Resources Template

Parameters:
  GroupName:
    Description: Name of the IAM Group
    Type: String
  UserName:
    Description: Name of the IAM User
    Type: String

Resources:
  MyIAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName

  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !GetAtt MyIAMGroup.Arn  # Associate the IAM Group with the Instance Profile
    DependsOn: MyIAMGroup