kind: environment
environment_name: Simple TF
state: active
owner_email: yakir.l@quali.com
blueprint:
  name: simple-tf-yakir
  repository_name: test-spec2-public
  commit: d908088
inputs:
  compute_service_name: aks-prod-2  
tags: {}
grains: {}
