apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: {{ .Values.InstanceName }}-{{ .Values.EnvironmentID }}
spec:
  forProvider:
    region: eu-west-1
    ami: ami-0e42de9d667b232f7  # ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20230531
    instanceType: t3.micro
    # securityGroupRefs:
    #   - name: sample-cluster-sg
    # subnetIdRef:
    #   name: sample-subnet1  
    tags:
      Name: {{ .Values.InstanceName }}-{{ .Values.EnvironmentID }}
  providerConfigRef:
    name: default