apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.BucketName }}-{{ .Values.EnvironmentID }}
spec:
  forProvider:  
    region: {{ .Values.AWSRegion }}
  providerConfigRef:
    name: default