apiVersion: v1
kind: Pod
metadata:
  name: docker-builder
spec:
  containers:
  - name: docker
    image: docker:latest
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    - name: docker-config
      mountPath: /root/.docker
    securityContext:
      privileged: true
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
  - name: docker-config
    secret:
      secretName: regcred
