apiVersion: batch/v1
kind: Job
metadata:
  generateName: sleep-before-sync-
  # name: sleep-before-sync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: bash:latest
        command:
          - "sleep"
          - "60"
      restartPolicy: Never
  backoffLimit: 1