AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack 2

Parameters:
  SecurityGroupId:
    Type: String
  SubnetId:
    Type: String
  ImageId:
    Type: AWS::EC2::Image::Id

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      ImageId: !Ref ImageId  # Use the ImageId parameter

  SubnetResource:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCId
      CidrBlock: 10.0.1.0/24  # Replace with the desired subnet CIDR

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
