apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.BucketName }}-{{ .Values.EnvironmentID }}
spec:
  forProvider:  
    locationConstraint: {{ .Values.AWSRegion }}
    acl: {{ .Values.BucketACL}}
    publicAccessBlockConfiguration:
      blockPublicAcls: false
      blockPublicPolicy: false
      ignorePublicAcls: false
      restrictPublicBuckets: false
    objectOwnership: 'ObjectWriter'
  providerConfigRef:
    name: default