---
- hosts: all
  collections:
    - torque.collections
  tasks:
  - name: Print Hello World
    debug: msg="Hello {{name}}"

  - name: Export outputs
    export_torque_outputs:
      outputs: 
        output1: "my output"