spec_version: 2
description: Blueprint for nginx helm chart 

inputs:
  agent:
    type: agent
  target-namespace:
    type: string
    default: "sveta-test"

grains:
  nginx:
    kind: helm
    spec:
      source:
        store: test-spec2-public
        path: helm/nginx-test
      agent:
        name: '{{ .inputs.agent }}'
        service-account: remote-cluster-accessor
        kubernetes:
          permissions:
            # secret-namespace is the runner namespace which is the agent's default namespace
            secret-name: playground-config
            destination-context-name: playground-eks
      target-namespace: '{{ inputs.target-namespace }}'
      commands:
        - dep up helm/nginx-test
