spec_version: 2
description: Blueprint with nginx kubernetes grain.

inputs:
  agent:
    type: agent
  target-namespace:
    type: string
    default: "sveta-test"

grains:
  nginx:
    kind: kubernetes
    spec:
      sources:
      - store: test-spec2-public
        path: manifests/nginx1/nginxmanifest.yaml
      agent:
        name: '{{ .inputs.agent }}'
        kubernetes:
          permissions:
            # secret-namespace is the runner namespace which is the agent's default namespace
            secret-name: playground-config
            destination-context-name: playground-eks
      target-namespace: '{{ inputs.target-namespace }}'
